ensure default values have the same type as values retrieved from environment
foxyblue/py-envconf pull request #9
Opened 2022-06-20 05:16 UTC by antonysouthworth-halter

Mainly this is just to reduce the chance of a user getting tripped up on #8 if they specify a param like `WINDOW_END = param.Datetime(default="2022-05-02T23:51:23Z")` (if `WINDOW_END` envvar is not provided, `config.WINDOW_END` will be a `str` instead of a `datetime`).

But I could imagine similar classes of errors cropping up if the default value for a `param.Int` was a `float`, or vice-versa `param.Float` was an `int`.

2022-06-21 09:44 UTC, foxyblue requested changes
I'm not 100% sure about this change, mainly because if we run into a case where `_cast(_cast(default))` fails we restrict the user from providing the expected type to `default`.

Maybe a datetime is an example.

Maybe a method other than `_cast` would be more suitable, that defaults to using `_cast`.

2022-06-21 09:44 UTC, foxyblue commented on envconfig/param.py
> +
Needs test cases.

2022-06-21 09:44 UTC, foxyblue commented on envconfig/param.py
> +            self.default = None
```python
self.default = default if default is None else self._cast(default)
```

2025-04-17 02:56 UTC, antonysouthworth-halter commented
closing as stale and obviously I have not found time to come back to it

2025-04-17 02:56 UTC, closed without merging